// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xpgmeejnbjlrctwgsxkk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhwZ21lZWpuYmpscmN0d2dzeGtrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc1ODg0NTQsImV4cCI6MjA3MzE2NDQ1NH0.qSG6U2O0L0dZK6XCEeauPzmirEUd0r8qlLrWRveejdE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});